### ISSUE TITLE
`lexical_cast` doesn't recognize `std::string_view` or `boost::string_view`

### ISSUE THREAD

**Issue by pdimov** [boostorg/lexical_cast#30]
As per title; `lexical_cast` has specializations for string types, but not for string view types. Reported on the C++ Slack.

**Comment by sehe** [comment]
Is this still current? I have just used `boost::convert::try_lexical_convert` just fine with both `std::string_view` and `boost::iterator_range<>`, so it would seem this has been fixed somewhere before 1.78.0?

**Comment by pdimov** [comment]
I think that it's still current, yes. Looking at https://godbolt.org/z/WMa7vhnT9, the function `f1` that uses a string goes directly to `boost::detail::lcast_ret_unsigned<std::char_traits<char>, unsigned int, char>::convert()`, whereas the two functions using string views take the generic path using a stream.

Similarly, in https://godbolt.org/z/9W6M1c35e, `f1` does a straight string copy, whereas `f2` and `f3` go through the slow stream path.

**Comment by sehe** [comment]
Ah. I completely misunderstood the problem description then. It's not that the conversions aren't supported, it's that they don't generate optimal code. The negative examples might actually be good addition for the original description.

**Comment by pdimov** [comment]
Edited to supply the code examples in case the CE links disappear.

**Comment by apolukhin** [comment]
Merged to master branch.

Many thanks for the PR!
