### ISSUE TITLE
GCC suggest-override warning

### ISSUE THREAD

**Issue by EugeneZelenko** [boostorg/lexical_cast#34]
Warning when Boost 1.72 is built with GCC 7.5 with `-Wsuggest-override` added to `cxxflags`:

<pre>
./boost/lexical_cast/bad_lexical_cast.hpp:54:29: warning: ‘virtual const char* boost::bad_lexical_cast::what() const’ can be marked override [-Wsuggest-override]
</pre>

`BOOST_OVERRIDE` was introduced in https://github.com/boostorg/config/commit/ffe4e0f5a448578cce14e3eed0cf7163333a81d9.

**Comment by apolukhin** [comment]
Thanks for the report!

**Comment by EugeneZelenko** [comment]
Thank you for fix!
