### ISSUE TITLE
boost::filesystem::path with witespaces

### ISSUE THREAD

**Issue by ohhmm** [boostorg/lexical_cast#58]
boost::filesystem::path is being deserialized to the first whitespace occurrence.

**Comment by apolukhin** [comment]
Could you please provide a reproducer?

**Comment by ohhmm** [comment]
C:\Program Files on Windows deserialized to C:\Program

**Comment by apolukhin** [comment]
@ohhmm to what type are you deserializing? Is that std::string?

**Comment by apolukhin** [comment]
Is the path quoted or not? All the above cases are covered with tests:

https://github.com/boostorg/lexical_cast/blob/3433c34b43969f2d3fc7309d895ef66019e3cfc1/test/filesystem_test.cpp#L35-L51

What version of Boost are you using?

**Comment by ohhmm** [comment]
I reproduced it using boost::program_options where option type is boost::filesystem::path. Tried it with multiple versions of boost on Windows. Tried with both quotations enabled/disabled.

**Comment by apolukhin** [comment]
@ohhmm is your case not covered by the tests in
https://github.com/boostorg/lexical_cast/blob/3433c34b43969f2d3fc7309d895ef66019e3cfc1/test/filesystem_test.cpp#L35-L51

?

If not covered, please provide a reproducer
